---
title: "hw06-rasiimwe.rmd"
author: "Becky"
date: '2018-11-01'
output: github_document
---

2. Writing functions

> Pick one:

> Write one (or more) functions that do something useful to pieces of the Gapminder or Singer data. It is logical to think about computing on the mini-data frames corresponding to the data for each specific country, location, year, band, album, … This would pair well with the prompt below about working with a nested data frame, as you could apply your function there.
> Make it something you can’t easily do with built-in functions. Make it something that’s not trivial to do with the simple dplyr verbs. The linear regression function presented here is a good starting point. You could generalize that to do quadratic regression (include a squared term) or use robust regression, using MASS::rlm() or robustbase::lmrob().
If you plan to complete the homework where we build an R package, write a couple of experimental functions exploring some functionality that is useful to you in real life and that might form the basis of your personal package.


5. Work with a list

> Work through and write up a lesson from the [purrr tutorial](https://jennybc.github.io/purrr-tutorial/index.html):
> [Trump Android Tweets](https://jennybc.github.io/purrr-tutorial/ls08_trump-tweets.html)
> [Simplifying data from a list of GitHub users](https://jennybc.github.io/purrr-tutorial/ls02_map-extraction-advanced.html)